from __future__ import annotations

from ._helpers import _BASE as _BASE
from ._helpers import _USER_DATA as _USER_DATA
from ._helpers import _load_text_file as _load_text_file
from ._helpers import _load_character_manifest as _load_character_manifest

from .ui_settings import (
    BACKGROUND_DIR as BACKGROUND_DIR,
    CURSOR_BLINK_INTERVAL_MS as CURSOR_BLINK_INTERVAL_MS,
    CURSOR_CHAR as CURSOR_CHAR,
    DISPLAY_BOTTOM_RATIO as DISPLAY_BOTTOM_RATIO,
    DISPLAY_LEFT_RATIO as DISPLAY_LEFT_RATIO,
    DISPLAY_RIGHT_RATIO as DISPLAY_RIGHT_RATIO,
    DISPLAY_TOP_RATIO as DISPLAY_TOP_RATIO,
    FONT_SIZE as FONT_SIZE,
    FULLSCREEN_BASE_HEIGHT as FULLSCREEN_BASE_HEIGHT,
    FULLSCREEN_BASE_WIDTH as FULLSCREEN_BASE_WIDTH,
    FULLSCREEN_MAX_SCALE as FULLSCREEN_MAX_SCALE,
    FULLSCREEN_MIN_FONT_SIZE as FULLSCREEN_MIN_FONT_SIZE,
    LINE_SPACING as LINE_SPACING,
    MASK_CENTER_OPACITY as MASK_CENTER_OPACITY,
    MASK_SIDE_FADE_END_RATIO as MASK_SIDE_FADE_END_RATIO,
    MASK_SIDE_FADE_START_RATIO as MASK_SIDE_FADE_START_RATIO,
    MUSIC_DIR as MUSIC_DIR,
    OVERLAY_OPACITY as OVERLAY_OPACITY,
    SUPPORTED_EXTENSIONS as SUPPORTED_EXTENSIONS,
    TEXT_COLOR as TEXT_COLOR,
    TEXT_OUTLINE_COLOR as TEXT_OUTLINE_COLOR,
    TEXT_OUTLINE_WIDTH as TEXT_OUTLINE_WIDTH,
    TEXT_PADDING as TEXT_PADDING,
    TYPEWRITER_INTERVAL_MS as TYPEWRITER_INTERVAL_MS,
    WINDOW_HEIGHT as WINDOW_HEIGHT,
    WINDOW_WIDTH as WINDOW_WIDTH,
)

from .animation_settings import (
    AFTER_FADE_OUT_DELAY_MS as AFTER_FADE_OUT_DELAY_MS,
    ANIMATION_TICK_MS as ANIMATION_TICK_MS,
    BEFORE_FADE_IN_DELAY_MS as BEFORE_FADE_IN_DELAY_MS,
    EMOTION_RESET_INTERVAL_MS as EMOTION_RESET_INTERVAL_MS,
    FOREGROUND_FADE_IN_DURATION_MS as FOREGROUND_FADE_IN_DURATION_MS,
    FOREGROUND_FADE_OUT_DURATION_MS as FOREGROUND_FADE_OUT_DURATION_MS,
    IDLE_RETURN_DELAY_MS as IDLE_RETURN_DELAY_MS,
    PAGE_TURN_FADE_IN_DURATION_MS as PAGE_TURN_FADE_IN_DURATION_MS,
    PAGE_TURN_FADE_OUT_DURATION_MS as PAGE_TURN_FADE_OUT_DURATION_MS,
    PORTRAIT_FADE_DURATION_MS as PORTRAIT_FADE_DURATION_MS,
    SEGMENT_GAP_INTERVAL_MS as SEGMENT_GAP_INTERVAL_MS,
)

from .api_settings import (
    API_BASE_URL as API_BASE_URL,
    API_KEY_ENV_VAR as API_KEY_ENV_VAR,
    API_MODEL as API_MODEL,
    MIN_REPLY_CHARS as MIN_REPLY_CHARS,
    PROVIDERS as PROVIDERS,
    resolve_api_config as resolve_api_config,
)

from .character_settings import (
    CHARACTER_CENTER_X_RATIO as CHARACTER_CENTER_X_RATIO,
    CHARACTER_BASELINE_Y_RATIO as CHARACTER_BASELINE_Y_RATIO,
    CHARACTER_DIR as CHARACTER_DIR,
    CHARACTER_DRESS_DIR as CHARACTER_DRESS_DIR,
    CHARACTER_EMOTIONS as CHARACTER_EMOTIONS,
    CHARACTER_MAX_WIDTH_RATIO as CHARACTER_MAX_WIDTH_RATIO,
    CHARACTER_MAX_HEIGHT_RATIO as CHARACTER_MAX_HEIGHT_RATIO,
    GENIE_CHARACTER_NAME as GENIE_CHARACTER_NAME,
    GENIE_MODEL_LANGUAGE as GENIE_MODEL_LANGUAGE,
    GENIE_ONNX_MODEL_DIR as GENIE_ONNX_MODEL_DIR,
    GENIE_REFERENCE_AUDIO_DIR as GENIE_REFERENCE_AUDIO_DIR,
    GENIE_REFERENCE_LANGUAGE as GENIE_REFERENCE_LANGUAGE,
    STATE_TO_ASSET as STATE_TO_ASSET,
    get_character_dir as get_character_dir,
    get_character_name as get_character_name,
    load_dress_config as load_dress_config,
    _default_dress_config as _default_dress_config,
)

from .storage_settings import (
    GENIE_AUDIO_BYTES_PER_SAMPLE as GENIE_AUDIO_BYTES_PER_SAMPLE,
    GENIE_AUDIO_CHANNELS as GENIE_AUDIO_CHANNELS,
    GENIE_AUDIO_SAMPLE_RATE as GENIE_AUDIO_SAMPLE_RATE,
    GENIE_SERVER_HOST as GENIE_SERVER_HOST,
    GENIE_SERVER_PORT as GENIE_SERVER_PORT,
    HISTORY_FILE_PATH as HISTORY_FILE_PATH,
    MEMORY_STATE_FILE_PATH as MEMORY_STATE_FILE_PATH,
    SETTINGS_FILE_PATH as SETTINGS_FILE_PATH,
    TEMP_AUDIO_DIR as TEMP_AUDIO_DIR,
)

from .prompt_settings import (
    DEFAULT_FIXED_REQUIREMENTS_PROMPT as DEFAULT_FIXED_REQUIREMENTS_PROMPT,
    DEFAULT_ROLE_PROMPT as DEFAULT_ROLE_PROMPT,
    DEFAULT_USER_PROFILE_PROMPT as DEFAULT_USER_PROFILE_PROMPT,
    MEMORY_L1_TURNS as MEMORY_L1_TURNS,
    MEMORY_L2_MAX_SUMMARY_CHARS as MEMORY_L2_MAX_SUMMARY_CHARS,
    MEMORY_L2_MIN_SUMMARY_CHARS as MEMORY_L2_MIN_SUMMARY_CHARS,
    MEMORY_L2_RECENT_TURNS as MEMORY_L2_RECENT_TURNS,
    MEMORY_L2_TRIGGER_EVERY as MEMORY_L2_TRIGGER_EVERY,
    MEMORY_STRICT_JSON_GUARD_PROMPT as MEMORY_STRICT_JSON_GUARD_PROMPT,
    MEMORY_SUMMARY_PROMPT as MEMORY_SUMMARY_PROMPT,
    SYSTEM_PROMPT as SYSTEM_PROMPT,
)
