from __future__ import annotations


# 切片调度相关时间。
SEGMENT_GAP_INTERVAL_MS = 1000
IDLE_RETURN_DELAY_MS = 1000
EMOTION_RESET_INTERVAL_MS = 60000

# 角色切图与前景层动画时间。
PORTRAIT_FADE_DURATION_MS = 300
FOREGROUND_FADE_OUT_DURATION_MS = 150
AFTER_FADE_OUT_DELAY_MS = 100
BEFORE_FADE_IN_DELAY_MS = 300
FOREGROUND_FADE_IN_DURATION_MS = 150
ANIMATION_TICK_MS = 16

# 仅翻页（不切角色）时的淡出/淡入时间。
PAGE_TURN_FADE_OUT_DURATION_MS = 220
PAGE_TURN_FADE_IN_DURATION_MS = 180
