from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Protocol, Optional

from PySide6.QtCore import QRect, QRectF, QTimer
from PySide6.QtGui import QFont, QPainter, QPixmap

from chat_app.core.window_runtime import VirtualTimer

if TYPE_CHECKING:
    from chat_app.audio.audio_manager import AudioManager
    from chat_app.audio.tts_client import GenieTTSClient, TtsWarmupThread
    from chat_app.audio.tts_pipeline import TtsPipelineManager
    from chat_app.core.state_machine import ChatStateMachine
    from chat_app.data.history_store import ChatHistoryStore, HistoryRecord
    from chat_app.data.settings_store import AppSettings, SettingsStore, MemoryState
    from chat_app.extensions import ExtensionManager
    from chat_app.services.api_client import ChatRequestThread, MemorySummaryThread
    from chat_app.ui.backgrounds import BackgroundDrawer


class WindowProtocol(Protocol):
    """BackgroundWindow 的共享接口协议。

    mixin 之间通过 self.xxx 跨文件访问的所有属性和方法都在此声明。
    任何实现此 Protocol 的类必须提供以下所有成员。

    按提供方分组：
    - window.py：大部分基本状态和所有的服务
    - InputMixin：输入处理
    - DialogueMixin：对话逻辑
    - AnimationMixin：动画调度
    - CharacterMixin：立绘管理
    - TextRenderMixin：文字渲染
    - AudioMixin：TTS 协调
    - BackgroundMixin：背景管理
    - MemoryMixin：记忆管理
    """

    # ── 基础状态 (window.py _init_basic_state) ──────────────────────────
    _loading: bool
    _toast_message: str
    background_dir: Path
    backgrounds: list[Path]
    current_background: Path | None
    current_pixmap: QPixmap
    scaled_background_pixmap: QPixmap
    overlay_enabled: bool
    chat_entries: list[str]
    cached_chat_lines: list[str]
    wrap_cache: dict[tuple[str, int], list[str]]
    text_pixmap_cache: dict[str, QPixmap]
    _line_runs_dirty: bool
    _cursor_rect_dirty: bool
    _render_line_runs_cache: list[list[tuple[str, float]]]
    _all_draw_lines_cache: list[str]
    _cursor_rect_cache: QRectF
    current_input: str
    preedit_text: str
    cursor_caret: int
    current_reply_full: str
    current_reply_visible: str
    current_narration: str
    top_level_emotion: str
    pending_reply_segments: list[dict[str, str]]
    current_dialogue_page_text: str
    current_dialogue_base_line_count: int
    cursor_visible: bool
    request_thread: ChatRequestThread | None
    memory_summary_thread: MemorySummaryThread | None
    tts_client: GenieTTSClient
    tts_warmup_thread: TtsWarmupThread | None
    current_segment_requires_transition: bool
    current_segment_is_followup: bool
    current_dialogue_segment_index: int
    pending_page_turn_before_next_segment: bool
    last_user_message: str
    is_fullscreen: bool
    scale_factor: float
    _saved_geometry: QRect | None
    _saved_flags: int | None
    _active_overlay: str | None

    # ── UI / 文本状态 (window.py _init_ui_state) ────────────────────────
    text_demote_target_alpha: float
    text_demote_duration_ms: float
    user_entry_alpha: float
    latest_user_line_count: int
    dialogue_history_stable_len: int
    dialogue_demoting_end: int
    dialogue_demoting_alpha: float
    user_fade_start_alpha: float
    dialogue_fade_start_alpha: float
    text_fade_progress: float
    pending_idle_after_text_demote: bool

    # ── 字体 / 图层 (window.py _init_ui_state) ──────────────────────────
    text_font: QFont
    previous_character_pixmap: QPixmap
    next_character_pixmap: QPixmap
    text_layer_alpha: float
    overlay_alpha: float
    ui_visibility_factor: float
    _background_drawer_active: bool
    drawer_trigger_margin_px: int
    drawer_open_delay_ms: int
    portrait_blend_progress: float
    animation_phase: str
    pending_resume_action: object | None

    # ── 角色状态 (window.py _init_character_state) ──────────────────────
    current_dress: str
    _dress_config: dict
    character_images: dict
    character_indices: dict
    character_emotion: str
    character_state: str
    character_pixmap: QPixmap
    character_draw_cache: dict[int, QRectF]

    # ── 服务 (window.py _build_context) ──────────────────────────────────
    chat_state: ChatStateMachine
    history_store: ChatHistoryStore
    history_records: list[HistoryRecord]
    settings_store: SettingsStore
    settings: AppSettings
    memory_state: MemoryState
    tts_pipeline: TtsPipelineManager
    audio_manager: AudioManager
    extension_manager: ExtensionManager
    context: object

    # ── 定时器 (window.py _init_timers) ──────────────────────────────────
    narration_wait_timer: QTimer
    cursor_timer: VirtualTimer
    typewriter_timer: VirtualTimer
    page_turn_timer: QTimer
    idle_timer: QTimer
    emotion_reset_timer: QTimer
    animation_timer: VirtualTimer
    text_fade_timer: VirtualTimer
    render_timer: QTimer
    drawer_trigger_timer: QTimer

    # ── UI 子组件 (window.py _setup_window) ──────────────────────────────
    background_drawer: BackgroundDrawer

    # ══════════════════════════════════════════════════════════════════════
    # 方法
    # ══════════════════════════════════════════════════════════════════════

    # ── QWidget (来自 Qt) ────────────────────────────────────────────────
    def update(self, *args, **kwargs) -> None: ...
    def width(self) -> int: ...
    def height(self) -> int: ...
    def rect(self) -> QRect: ...
    def size(self) -> object: ...
    def mapFromGlobal(self, pos: object) -> object: ...
    def devicePixelRatioF(self) -> float: ...
    def geometry(self) -> QRect: ...
    def setGeometry(self, *args, **kwargs) -> None: ...
    def setWindowFlags(self, flags: int) -> None: ...
    def windowFlags(self) -> int: ...
    def showFullScreen(self) -> None: ...
    def show(self) -> None: ...
    def setFixedSize(self, w: int, h: int) -> None: ...
    def setMouseTracking(self, flag: bool) -> None: ...
    def setFocusPolicy(self, policy: object) -> None: ...
    def setInputMethodHints(self, hints: object) -> None: ...
    def activateWindow(self) -> None: ...
    def setAttribute(self, attr: object, on: bool = True) -> None: ...
    def raise_(self) -> None: ...

    # ── InputMixin ──────────────────────────────────────────────────────
    def keyPressEvent(self, event: object) -> None: ...
    def inputMethodEvent(self, event: object) -> None: ...
    def inputMethodQuery(self, query: object) -> object: ...
    def focusInEvent(self, event: object) -> None: ...
    def focusOutEvent(self, event: object) -> None: ...
    def mousePressEvent(self, event: object) -> None: ...
    def restore_input_context(self) -> None: ...
    def _refresh_ime(self) -> None: ...
    def _is_ui_input_locked(self) -> bool: ...

    # ── DialogueMixin ────────────────────────────────────────────────────
    def quote_text(self, text: str) -> str: ...
    def quoted_input(self) -> str: ...
    def normalize_reply_segments(self, payload: dict) -> list[dict[str, str]]: ...
    def wrapped_lines_for_entries(self, entries: list[str]) -> list[str]: ...
    def rebuild_cached_chat_lines(self) -> None: ...
    def append_chat_entry(self, entry: str) -> None: ...
    def clear_chat_entries(self) -> None: ...
    def append_or_extend_dialogue_entry(self, segment_text: str) -> None: ...
    def lines_fit_in_display(self, lines: list[str]) -> bool: ...
    def submit_input(self) -> None: ...
    def on_reply_ready(self, payload: dict) -> None: ...
    def on_reply_failed(self, error_text: str) -> None: ...
    def on_request_finished(self) -> None: ...
    def _after_react(self) -> None: ...
    def on_narration_wait_elapsed(self) -> None: ...
    def will_next_segment_overflow(self) -> bool: ...
    def on_segment_gap_elapsed(self) -> None: ...
    def start_next_reply_segment(self) -> None: ...
    def start_reply_output(self) -> None: ...
    def advance_typewriter(self) -> None: ...
    def return_to_idle(self) -> None: ...
    def finish_return_to_idle(self) -> None: ...
    def clear_screen_text(self) -> None: ...
    def contextMenuEvent(self, event: object) -> None: ...
    def open_history_dialog(self) -> None: ...
    def open_settings_dialog(self) -> None: ...

    # ── AnimationMixin ──────────────────────────────────────────────────
    def _refresh_render_timer_running(self) -> None: ...
    def _on_render_tick(self) -> None: ...
    def toggle_cursor(self) -> None: ...
    def begin_portrait_transition(
        self, new_pixmap: QPixmap, resume_action=None, quick: bool = False
    ) -> None: ...
    def start_page_turn_transition(self) -> None: ...
    def start_text_demote_transition(self) -> None: ...
    def advance_animation(self) -> None: ...
    def advance_text_fade(self) -> None: ...

    # ── CharacterMixin ──────────────────────────────────────────────────
    def character_asset_state(self) -> str: ...
    def character_candidates(self, emotion: str, asset_state: str) -> list[Path]: ...
    def next_character_image_path(self) -> Path | None: ...
    def refresh_character_portrait(self) -> None: ...
    def set_character_state(self, state: str, resume_action=None, quick: bool = False) -> None: ...
    def set_character_emotion(self, emotion: str) -> None: ...
    def reset_emotion_to_normal(self) -> None: ...
    def character_draw_rect(self, pixmap: QPixmap) -> QRectF: ...
    def draw_character_layer(self, painter: QPainter) -> None: ...

    # ── TextRenderMixin ──────────────────────────────────────────────────
    @property
    def effective_font_size(self) -> int: ...
    def display_rect(self) -> QRect: ...
    def text_metrics(self) -> object: ...
    def line_height(self) -> float: ...
    def content_rect(self) -> QRectF: ...
    def _mark_layout_dirty(self) -> None: ...
    def _mark_cursor_dirty(self) -> None: ...
    def _ensure_render_cache(self) -> None: ...
    def all_draw_lines(self) -> list[str]: ...
    def cursor_rect(self) -> QRectF: ...
    def wrap_text(self, text: str) -> list[str]: ...
    def wrap_alpha_spans(self, spans: list[tuple[str, float]]) -> list[list[tuple[str, float]]]: ...
    def build_render_line_runs(self) -> list[list[tuple[str, float]]]: ...
    def get_text_pixmap(self, text: str) -> QPixmap: ...
    def draw_outlined_text(
        self, painter: QPainter, x: float, baseline_y: float,
        text: str, alpha_factor: float = 1.0,
    ) -> None: ...
    def paintEvent(self, event: object) -> None: ...

    # ── AudioMixin ──────────────────────────────────────────────────────
    def _setup_audio_connections(self) -> None: ...
    def start_tts_warmup(self) -> None: ...
    def on_tts_warmup_failed(self, error_text: str) -> None: ...
    def begin_tts_for_reply(self, segment: dict[str, str], start_when_ready: bool) -> None: ...
    def pump_synthesis_queue(self) -> None: ...
    def queue_prefetch_next_segment(self) -> None: ...
    def start_segment_after_audio_ready(self, segment: dict[str, str]) -> None: ...
    def _on_tts_audio_ready(self, segment: dict[str, str], start_when_ready: bool) -> None: ...
    def _on_tts_synthesis_failed(self, segment: dict[str, str], start_when_ready: bool, error_text: str) -> None: ...
    def _on_audio_manager_finished(self) -> None: ...
    def _on_audio_manager_failed(self, error_msg: str) -> None: ...

    # ── BackgroundMixin ──────────────────────────────────────────────────
    def resolve_saved_background(self, saved_path_text: str) -> Path | None: ...
    def refresh_scaled_background(self) -> None: ...
    def set_background(self, image_path: Path, persist: bool = True) -> None: ...
    def set_overlay_enabled(self, enabled: bool) -> None: ...
    def draw_mask_layer(self, painter: QPainter) -> None: ...
    def _drawer_hidden_x(self) -> int: ...
    def _drawer_open_x(self) -> int: ...
    def _sync_ui_visibility_with_drawer(self) -> None: ...
    def _in_drawer_trigger_zone(self, pos: object) -> bool: ...
    def _open_background_drawer_from_trigger(self) -> None: ...
    def _should_close_drawer_for_pos(self, pos: object) -> bool: ...
    def _update_background_drawer_trigger(self, pos: object) -> None: ...
    def toggle_background_drawer(self) -> None: ...
    def _on_drawer_background_selected(self, image_path: Path) -> None: ...

    # ── MemoryMixin ────────────────────────────────────────────────────
    def _build_l1_memory_messages(self) -> list[dict[str, str]]: ...
    def _recent_turns_for_summary(self) -> list[dict[str, str]]: ...
    def _maybe_trigger_memory_summary(self) -> None: ...
    def _on_memory_summary_ready(self, summary_text: str) -> None: ...
    def _on_memory_summary_failed(self, error_text: str) -> None: ...

    # ── window.py 特有 ───────────────────────────────────────────────────
    def show_toast(self, message: str, duration_ms: int = 5000) -> None: ...
    def switch_dress(self, dress_name: str) -> None: ...
    def toggle_fullscreen(self) -> None: ...
    def closeEvent(self, event: object) -> None: ...
    def showEvent(self, event: object) -> None: ...
    def resizeEvent(self, event: object) -> None: ...
